language: python
sudo: false
cache: pip
dist: trusty
group: edge
python:
   - "2.7"
os:
  - linux
install:
  - "pip install -r requirements.txt"
  - "python setup.py build_ext --inplace"
  - "pip install -e ."
script:
  - "cat /proc/cpuinfo | grep flags | head -n 1"
  - "python -m pytest --tb=native spacy"
branches:
  except:
    - spacy.io
notifications:
  slack:
    secure: F8GvqnweSdzImuLL64TpfG0i5rYl89liyr9tmFVsHl4c0DNiDuGhZivUz0M1broS8svE3OPOllLfQbACG/4KxD890qfF9MoHzvRDlp7U+RtwMV/YAkYn8MGWjPIbRbX0HpGdY7O2Rc9Qy4Kk0T8ZgiqXYIqAz2Eva9/9BlSmsJQ=
  email: false
