[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython>=0.25",
    "cymem>=2.0.2,<2.1.0",
    "preshed>=3.0.2,<3.1.0",
    "murmurhash>=0.28.0,<1.1.0",
    "thinc>=8.0.0a44,<8.0.0a50",
    "blis>=0.4.0,<0.8.0",
    "pytokenizations",
    "pathy"
]
build-backend = "setuptools.build_meta"
