blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Python 3.10 Support
    url: https://github.com/explosion/spaCy/discussions/9418
    about: Python 3.10 wheels haven't been released yet, see the link for details.
  - name: ğŸ—¯ Discussions Forum
    url: https://github.com/explosion/spaCy/discussions
    about: Install issues, usage questions, general discussion and anything else that isn't a bug report.
  - name: ğŸ“– spaCy FAQ & Troubleshooting
    url: https://github.com/explosion/spaCy/discussions/8226
    about: Before you post, check out the FAQ for answers to common community questions!
  - name: ğŸ’« spaCy Usage Guides & API reference
    url: https://spacy.io/usage
    about: Everything you need to know about spaCy and how to use it.
  - name: ğŸ›  Submit a Pull Request
    url: https://github.com/explosion/spaCy/pulls
    about: Did you spot a mistake and know how to fix it? Feel free to submit a PR straight away!
